// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Pearogram.Models
{
    public partial class Product
    {
        [Key]
        public int productId { get; set; }
   
        [Required(ErrorMessage = "Product Name is Required")]
        [Display(Name = "Product Name")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Supplier must be string")]
        [Remote(action: "IsExists", controller: "Product", AdditionalFields = "SupplierID", ErrorMessage = "This product has been inserted before with the same supplier")]
        public string productName { get; set; }
        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "UPRN must be numeric")]
        public double? QuentityPerUnit { get; set; }
        [Required]
     
        [RegularExpression("^[0-9]*$", ErrorMessage = "UPRN must be numeric")]
        public int? ReorderLevel { get; set; }
        [Required]
       
        public int? SupplierID { get; set; }
        [Required]
     
        [RegularExpression("^[0-9]*$", ErrorMessage = "UPRN must be numeric")]
        public double? unitInStock { get; set; }
        [Required]
     
        [RegularExpression("^[0-9]*$", ErrorMessage = "UPRN must be numeric")]
        public double? UnitsInOrder { get; set; }

        [ForeignKey("SupplierID")]
        [InverseProperty("Products")]
        public virtual Supplier Supplier { get; set; }
    }
}